version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for cargo updates at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 10
