apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "redact_ex"
  description: "Utilities to redact sensitive data in Elixir projects"
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-developer-experience"
  system: prima.it
